// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/scality/file-reflector/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetadataReader creates a new instance of MockMetadataReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataReader {
	mock := &MockMetadataReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataReader is an autogenerated mock type for the MetadataReader type
type MockMetadataReader struct {
	mock.Mock
}

type MockMetadataReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataReader) EXPECT() *MockMetadataReader_Expecter {
	return &MockMetadataReader_Expecter{mock: &_m.Mock}
}

// ReadDir provides a mock function for the type MockMetadataReader
func (_mock *MockMetadataReader) ReadDir(ctx context.Context, relPath string) ([]string, error) {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, relPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, relPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataReader_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockMetadataReader_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockMetadataReader_Expecter) ReadDir(ctx interface{}, relPath interface{}) *MockMetadataReader_ReadDir_Call {
	return &MockMetadataReader_ReadDir_Call{Call: _e.mock.On("ReadDir", ctx, relPath)}
}

func (_c *MockMetadataReader_ReadDir_Call) Run(run func(ctx context.Context, relPath string)) *MockMetadataReader_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataReader_ReadDir_Call) Return(strings []string, err error) *MockMetadataReader_ReadDir_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockMetadataReader_ReadDir_Call) RunAndReturn(run func(ctx context.Context, relPath string) ([]string, error)) *MockMetadataReader_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockMetadataReader
func (_mock *MockMetadataReader) Stat(ctx context.Context, relPath string) (domain.FileNode, error) {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 domain.FileNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.FileNode, error)); ok {
		return returnFunc(ctx, relPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.FileNode); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		r0 = ret.Get(0).(domain.FileNode)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, relPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataReader_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockMetadataReader_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockMetadataReader_Expecter) Stat(ctx interface{}, relPath interface{}) *MockMetadataReader_Stat_Call {
	return &MockMetadataReader_Stat_Call{Call: _e.mock.On("Stat", ctx, relPath)}
}

func (_c *MockMetadataReader_Stat_Call) Run(run func(ctx context.Context, relPath string)) *MockMetadataReader_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataReader_Stat_Call) Return(fileNode domain.FileNode, err error) *MockMetadataReader_Stat_Call {
	_c.Call.Return(fileNode, err)
	return _c
}

func (_c *MockMetadataReader_Stat_Call) RunAndReturn(run func(ctx context.Context, relPath string) (domain.FileNode, error)) *MockMetadataReader_Stat_Call {
	_c.Call.Return(run)
	return _c
}
