// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMetadataWriter creates a new instance of MockMetadataWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataWriter {
	mock := &MockMetadataWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataWriter is an autogenerated mock type for the MetadataWriter type
type MockMetadataWriter struct {
	mock.Mock
}

type MockMetadataWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataWriter) EXPECT() *MockMetadataWriter_Expecter {
	return &MockMetadataWriter_Expecter{mock: &_m.Mock}
}

// Chmod provides a mock function for the type MockMetadataWriter
func (_mock *MockMetadataWriter) Chmod(ctx context.Context, relPath string, mode fs.FileMode) error {
	ret := _mock.Called(ctx, relPath, mode)

	if len(ret) == 0 {
		panic("no return value specified for Chmod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, fs.FileMode) error); ok {
		r0 = returnFunc(ctx, relPath, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataWriter_Chmod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chmod'
type MockMetadataWriter_Chmod_Call struct {
	*mock.Call
}

// Chmod is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
//   - mode fs.FileMode
func (_e *MockMetadataWriter_Expecter) Chmod(ctx interface{}, relPath interface{}, mode interface{}) *MockMetadataWriter_Chmod_Call {
	return &MockMetadataWriter_Chmod_Call{Call: _e.mock.On("Chmod", ctx, relPath, mode)}
}

func (_c *MockMetadataWriter_Chmod_Call) Run(run func(ctx context.Context, relPath string, mode fs.FileMode)) *MockMetadataWriter_Chmod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 fs.FileMode
		if args[2] != nil {
			arg2 = args[2].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataWriter_Chmod_Call) Return(err error) *MockMetadataWriter_Chmod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataWriter_Chmod_Call) RunAndReturn(run func(ctx context.Context, relPath string, mode fs.FileMode) error) *MockMetadataWriter_Chmod_Call {
	_c.Call.Return(run)
	return _c
}

// Chown provides a mock function for the type MockMetadataWriter
func (_mock *MockMetadataWriter) Chown(ctx context.Context, relPath string, uid int, gid int) error {
	ret := _mock.Called(ctx, relPath, uid, gid)

	if len(ret) == 0 {
		panic("no return value specified for Chown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) error); ok {
		r0 = returnFunc(ctx, relPath, uid, gid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataWriter_Chown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chown'
type MockMetadataWriter_Chown_Call struct {
	*mock.Call
}

// Chown is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
//   - uid int
//   - gid int
func (_e *MockMetadataWriter_Expecter) Chown(ctx interface{}, relPath interface{}, uid interface{}, gid interface{}) *MockMetadataWriter_Chown_Call {
	return &MockMetadataWriter_Chown_Call{Call: _e.mock.On("Chown", ctx, relPath, uid, gid)}
}

func (_c *MockMetadataWriter_Chown_Call) Run(run func(ctx context.Context, relPath string, uid int, gid int)) *MockMetadataWriter_Chown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMetadataWriter_Chown_Call) Return(err error) *MockMetadataWriter_Chown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataWriter_Chown_Call) RunAndReturn(run func(ctx context.Context, relPath string, uid int, gid int) error) *MockMetadataWriter_Chown_Call {
	_c.Call.Return(run)
	return _c
}
