// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"
	"io/fs"

	"github.com/scality/file-reflector/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTargetWriter creates a new instance of MockTargetWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTargetWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTargetWriter {
	mock := &MockTargetWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTargetWriter is an autogenerated mock type for the TargetWriter type
type MockTargetWriter struct {
	mock.Mock
}

type MockTargetWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTargetWriter) EXPECT() *MockTargetWriter_Expecter {
	return &MockTargetWriter_Expecter{mock: &_m.Mock}
}

// Chmod provides a mock function for the type MockTargetWriter
func (_mock *MockTargetWriter) Chmod(ctx context.Context, relPath string, mode fs.FileMode) error {
	ret := _mock.Called(ctx, relPath, mode)

	if len(ret) == 0 {
		panic("no return value specified for Chmod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, fs.FileMode) error); ok {
		r0 = returnFunc(ctx, relPath, mode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTargetWriter_Chmod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chmod'
type MockTargetWriter_Chmod_Call struct {
	*mock.Call
}

// Chmod is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
//   - mode fs.FileMode
func (_e *MockTargetWriter_Expecter) Chmod(ctx any, relPath any, mode any) *MockTargetWriter_Chmod_Call {
	return &MockTargetWriter_Chmod_Call{Call: _e.mock.On("Chmod", ctx, relPath, mode)}
}

func (_c *MockTargetWriter_Chmod_Call) Run(run func(ctx context.Context, relPath string, mode fs.FileMode)) *MockTargetWriter_Chmod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 fs.FileMode
		if args[2] != nil {
			arg2 = args[2].(fs.FileMode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTargetWriter_Chmod_Call) Return(err error) *MockTargetWriter_Chmod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTargetWriter_Chmod_Call) RunAndReturn(run func(ctx context.Context, relPath string, mode fs.FileMode) error) *MockTargetWriter_Chmod_Call {
	_c.Call.Return(run)
	return _c
}

// Chown provides a mock function for the type MockTargetWriter
func (_mock *MockTargetWriter) Chown(ctx context.Context, relPath string, uid int, gid int) error {
	ret := _mock.Called(ctx, relPath, uid, gid)

	if len(ret) == 0 {
		panic("no return value specified for Chown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) error); ok {
		r0 = returnFunc(ctx, relPath, uid, gid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTargetWriter_Chown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chown'
type MockTargetWriter_Chown_Call struct {
	*mock.Call
}

// Chown is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
//   - uid int
//   - gid int
func (_e *MockTargetWriter_Expecter) Chown(ctx any, relPath any, uid any, gid any) *MockTargetWriter_Chown_Call {
	return &MockTargetWriter_Chown_Call{Call: _e.mock.On("Chown", ctx, relPath, uid, gid)}
}

func (_c *MockTargetWriter_Chown_Call) Run(run func(ctx context.Context, relPath string, uid int, gid int)) *MockTargetWriter_Chown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTargetWriter_Chown_Call) Return(err error) *MockTargetWriter_Chown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTargetWriter_Chown_Call) RunAndReturn(run func(ctx context.Context, relPath string, uid int, gid int) error) *MockTargetWriter_Chown_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockTargetWriter
func (_mock *MockTargetWriter) Hash(ctx context.Context, relPath string) ([32]byte, error) {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 [32]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([32]byte, error)); ok {
		return returnFunc(ctx, relPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) [32]byte); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([32]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, relPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTargetWriter_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockTargetWriter_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockTargetWriter_Expecter) Hash(ctx any, relPath any) *MockTargetWriter_Hash_Call {
	return &MockTargetWriter_Hash_Call{Call: _e.mock.On("Hash", ctx, relPath)}
}

func (_c *MockTargetWriter_Hash_Call) Run(run func(ctx context.Context, relPath string)) *MockTargetWriter_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTargetWriter_Hash_Call) Return(bytes [32]byte, err error) *MockTargetWriter_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockTargetWriter_Hash_Call) RunAndReturn(run func(ctx context.Context, relPath string) ([32]byte, error)) *MockTargetWriter_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Mkdir provides a mock function for the type MockTargetWriter
func (_mock *MockTargetWriter) Mkdir(ctx context.Context, relPath string, mode fs.FileMode, uid int, gid int) error {
	ret := _mock.Called(ctx, relPath, mode, uid, gid)

	if len(ret) == 0 {
		panic("no return value specified for Mkdir")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, fs.FileMode, int, int) error); ok {
		r0 = returnFunc(ctx, relPath, mode, uid, gid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTargetWriter_Mkdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mkdir'
type MockTargetWriter_Mkdir_Call struct {
	*mock.Call
}

// Mkdir is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
//   - mode fs.FileMode
//   - uid int
//   - gid int
func (_e *MockTargetWriter_Expecter) Mkdir(ctx any, relPath any, mode any, uid any, gid any) *MockTargetWriter_Mkdir_Call {
	return &MockTargetWriter_Mkdir_Call{Call: _e.mock.On("Mkdir", ctx, relPath, mode, uid, gid)}
}

func (_c *MockTargetWriter_Mkdir_Call) Run(run func(ctx context.Context, relPath string, mode fs.FileMode, uid int, gid int)) *MockTargetWriter_Mkdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 fs.FileMode
		if args[2] != nil {
			arg2 = args[2].(fs.FileMode)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockTargetWriter_Mkdir_Call) Return(err error) *MockTargetWriter_Mkdir_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTargetWriter_Mkdir_Call) RunAndReturn(run func(ctx context.Context, relPath string, mode fs.FileMode, uid int, gid int) error) *MockTargetWriter_Mkdir_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function for the type MockTargetWriter
func (_mock *MockTargetWriter) ReadDir(ctx context.Context, relPath string) ([]string, error) {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, relPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, relPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTargetWriter_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockTargetWriter_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockTargetWriter_Expecter) ReadDir(ctx any, relPath any) *MockTargetWriter_ReadDir_Call {
	return &MockTargetWriter_ReadDir_Call{Call: _e.mock.On("ReadDir", ctx, relPath)}
}

func (_c *MockTargetWriter_ReadDir_Call) Run(run func(ctx context.Context, relPath string)) *MockTargetWriter_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTargetWriter_ReadDir_Call) Return(strings []string, err error) *MockTargetWriter_ReadDir_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockTargetWriter_ReadDir_Call) RunAndReturn(run func(ctx context.Context, relPath string) ([]string, error)) *MockTargetWriter_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockTargetWriter
func (_mock *MockTargetWriter) Remove(ctx context.Context, relPath string) error {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTargetWriter_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockTargetWriter_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockTargetWriter_Expecter) Remove(ctx any, relPath any) *MockTargetWriter_Remove_Call {
	return &MockTargetWriter_Remove_Call{Call: _e.mock.On("Remove", ctx, relPath)}
}

func (_c *MockTargetWriter_Remove_Call) Run(run func(ctx context.Context, relPath string)) *MockTargetWriter_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTargetWriter_Remove_Call) Return(err error) *MockTargetWriter_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTargetWriter_Remove_Call) RunAndReturn(run func(ctx context.Context, relPath string) error) *MockTargetWriter_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockTargetWriter
func (_mock *MockTargetWriter) Stat(ctx context.Context, relPath string) (domain.FileNode, error) {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 domain.FileNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.FileNode, error)); ok {
		return returnFunc(ctx, relPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.FileNode); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		r0 = ret.Get(0).(domain.FileNode)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, relPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTargetWriter_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockTargetWriter_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockTargetWriter_Expecter) Stat(ctx any, relPath any) *MockTargetWriter_Stat_Call {
	return &MockTargetWriter_Stat_Call{Call: _e.mock.On("Stat", ctx, relPath)}
}

func (_c *MockTargetWriter_Stat_Call) Run(run func(ctx context.Context, relPath string)) *MockTargetWriter_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTargetWriter_Stat_Call) Return(fileNode domain.FileNode, err error) *MockTargetWriter_Stat_Call {
	_c.Call.Return(fileNode, err)
	return _c
}

func (_c *MockTargetWriter_Stat_Call) RunAndReturn(run func(ctx context.Context, relPath string) (domain.FileNode, error)) *MockTargetWriter_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// WriteAtomic provides a mock function for the type MockTargetWriter
func (_mock *MockTargetWriter) WriteAtomic(ctx context.Context, relPath string, src io.Reader, mode fs.FileMode, uid int, gid int) error {
	ret := _mock.Called(ctx, relPath, src, mode, uid, gid)

	if len(ret) == 0 {
		panic("no return value specified for WriteAtomic")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, fs.FileMode, int, int) error); ok {
		r0 = returnFunc(ctx, relPath, src, mode, uid, gid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTargetWriter_WriteAtomic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAtomic'
type MockTargetWriter_WriteAtomic_Call struct {
	*mock.Call
}

// WriteAtomic is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
//   - src io.Reader
//   - mode fs.FileMode
//   - uid int
//   - gid int
func (_e *MockTargetWriter_Expecter) WriteAtomic(ctx any, relPath any, src any, mode any, uid any, gid any) *MockTargetWriter_WriteAtomic_Call {
	return &MockTargetWriter_WriteAtomic_Call{Call: _e.mock.On("WriteAtomic", ctx, relPath, src, mode, uid, gid)}
}

func (_c *MockTargetWriter_WriteAtomic_Call) Run(run func(ctx context.Context, relPath string, src io.Reader, mode fs.FileMode, uid int, gid int)) *MockTargetWriter_WriteAtomic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 fs.FileMode
		if args[3] != nil {
			arg3 = args[3].(fs.FileMode)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockTargetWriter_WriteAtomic_Call) Return(err error) *MockTargetWriter_WriteAtomic_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTargetWriter_WriteAtomic_Call) RunAndReturn(run func(ctx context.Context, relPath string, src io.Reader, mode fs.FileMode, uid int, gid int) error) *MockTargetWriter_WriteAtomic_Call {
	_c.Call.Return(run)
	return _c
}
