// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockContentHasher creates a new instance of MockContentHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContentHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContentHasher {
	mock := &MockContentHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContentHasher is an autogenerated mock type for the ContentHasher type
type MockContentHasher struct {
	mock.Mock
}

type MockContentHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContentHasher) EXPECT() *MockContentHasher_Expecter {
	return &MockContentHasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type MockContentHasher
func (_mock *MockContentHasher) Hash(ctx context.Context, relPath string) ([32]byte, error) {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 [32]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([32]byte, error)); ok {
		return returnFunc(ctx, relPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) [32]byte); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([32]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, relPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockContentHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockContentHasher_Expecter) Hash(ctx any, relPath any) *MockContentHasher_Hash_Call {
	return &MockContentHasher_Hash_Call{Call: _e.mock.On("Hash", ctx, relPath)}
}

func (_c *MockContentHasher_Hash_Call) Run(run func(ctx context.Context, relPath string)) *MockContentHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContentHasher_Hash_Call) Return(bytes [32]byte, err error) *MockContentHasher_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockContentHasher_Hash_Call) RunAndReturn(run func(ctx context.Context, relPath string) ([32]byte, error)) *MockContentHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}
