// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockContentReader creates a new instance of MockContentReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContentReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContentReader {
	mock := &MockContentReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContentReader is an autogenerated mock type for the ContentReader type
type MockContentReader struct {
	mock.Mock
}

type MockContentReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContentReader) EXPECT() *MockContentReader_Expecter {
	return &MockContentReader_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type MockContentReader
func (_mock *MockContentReader) Open(ctx context.Context, relPath string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, relPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, relPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContentReader_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockContentReader_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockContentReader_Expecter) Open(ctx interface{}, relPath interface{}) *MockContentReader_Open_Call {
	return &MockContentReader_Open_Call{Call: _e.mock.On("Open", ctx, relPath)}
}

func (_c *MockContentReader_Open_Call) Run(run func(ctx context.Context, relPath string)) *MockContentReader_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContentReader_Open_Call) Return(readCloser io.ReadCloser, err error) *MockContentReader_Open_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockContentReader_Open_Call) RunAndReturn(run func(ctx context.Context, relPath string) (io.ReadCloser, error)) *MockContentReader_Open_Call {
	_c.Call.Return(run)
	return _c
}
