// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMatcher creates a new instance of MockMatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatcher {
	mock := &MockMatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMatcher is an autogenerated mock type for the Matcher type
type MockMatcher struct {
	mock.Mock
}

type MockMatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatcher) EXPECT() *MockMatcher_Expecter {
	return &MockMatcher_Expecter{mock: &_m.Mock}
}

// Matches provides a mock function for the type MockMatcher
func (_mock *MockMatcher) Matches(relPath string) bool {
	ret := _mock.Called(relPath)

	if len(ret) == 0 {
		panic("no return value specified for Matches")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(relPath)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMatcher_Matches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Matches'
type MockMatcher_Matches_Call struct {
	*mock.Call
}

// Matches is a helper method to define mock.On call
//   - relPath string
func (_e *MockMatcher_Expecter) Matches(relPath any) *MockMatcher_Matches_Call {
	return &MockMatcher_Matches_Call{Call: _e.mock.On("Matches", relPath)}
}

func (_c *MockMatcher_Matches_Call) Run(run func(relPath string)) *MockMatcher_Matches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMatcher_Matches_Call) Return(b bool) *MockMatcher_Matches_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMatcher_Matches_Call) RunAndReturn(run func(relPath string) bool) *MockMatcher_Matches_Call {
	_c.Call.Return(run)
	return _c
}
