// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEntryRemover creates a new instance of MockEntryRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEntryRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEntryRemover {
	mock := &MockEntryRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEntryRemover is an autogenerated mock type for the EntryRemover type
type MockEntryRemover struct {
	mock.Mock
}

type MockEntryRemover_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEntryRemover) EXPECT() *MockEntryRemover_Expecter {
	return &MockEntryRemover_Expecter{mock: &_m.Mock}
}

// Remove provides a mock function for the type MockEntryRemover
func (_mock *MockEntryRemover) Remove(ctx context.Context, relPath string) error {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEntryRemover_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockEntryRemover_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockEntryRemover_Expecter) Remove(ctx any, relPath any) *MockEntryRemover_Remove_Call {
	return &MockEntryRemover_Remove_Call{Call: _e.mock.On("Remove", ctx, relPath)}
}

func (_c *MockEntryRemover_Remove_Call) Run(run func(ctx context.Context, relPath string)) *MockEntryRemover_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEntryRemover_Remove_Call) Return(err error) *MockEntryRemover_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEntryRemover_Remove_Call) RunAndReturn(run func(ctx context.Context, relPath string) error) *MockEntryRemover_Remove_Call {
	_c.Call.Return(run)
	return _c
}
