// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockContentWriter creates a new instance of MockContentWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContentWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContentWriter {
	mock := &MockContentWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContentWriter is an autogenerated mock type for the ContentWriter type
type MockContentWriter struct {
	mock.Mock
}

type MockContentWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContentWriter) EXPECT() *MockContentWriter_Expecter {
	return &MockContentWriter_Expecter{mock: &_m.Mock}
}

// Mkdir provides a mock function for the type MockContentWriter
func (_mock *MockContentWriter) Mkdir(ctx context.Context, relPath string, mode fs.FileMode, uid int, gid int) error {
	ret := _mock.Called(ctx, relPath, mode, uid, gid)

	if len(ret) == 0 {
		panic("no return value specified for Mkdir")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, fs.FileMode, int, int) error); ok {
		r0 = returnFunc(ctx, relPath, mode, uid, gid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContentWriter_Mkdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mkdir'
type MockContentWriter_Mkdir_Call struct {
	*mock.Call
}

// Mkdir is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
//   - mode fs.FileMode
//   - uid int
//   - gid int
func (_e *MockContentWriter_Expecter) Mkdir(ctx any, relPath any, mode any, uid any, gid any) *MockContentWriter_Mkdir_Call {
	return &MockContentWriter_Mkdir_Call{Call: _e.mock.On("Mkdir", ctx, relPath, mode, uid, gid)}
}

func (_c *MockContentWriter_Mkdir_Call) Run(run func(ctx context.Context, relPath string, mode fs.FileMode, uid int, gid int)) *MockContentWriter_Mkdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 fs.FileMode
		if args[2] != nil {
			arg2 = args[2].(fs.FileMode)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockContentWriter_Mkdir_Call) Return(err error) *MockContentWriter_Mkdir_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContentWriter_Mkdir_Call) RunAndReturn(run func(ctx context.Context, relPath string, mode fs.FileMode, uid int, gid int) error) *MockContentWriter_Mkdir_Call {
	_c.Call.Return(run)
	return _c
}

// WriteAtomic provides a mock function for the type MockContentWriter
func (_mock *MockContentWriter) WriteAtomic(ctx context.Context, relPath string, src io.Reader, mode fs.FileMode, uid int, gid int) error {
	ret := _mock.Called(ctx, relPath, src, mode, uid, gid)

	if len(ret) == 0 {
		panic("no return value specified for WriteAtomic")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, fs.FileMode, int, int) error); ok {
		r0 = returnFunc(ctx, relPath, src, mode, uid, gid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContentWriter_WriteAtomic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteAtomic'
type MockContentWriter_WriteAtomic_Call struct {
	*mock.Call
}

// WriteAtomic is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
//   - src io.Reader
//   - mode fs.FileMode
//   - uid int
//   - gid int
func (_e *MockContentWriter_Expecter) WriteAtomic(ctx any, relPath any, src any, mode any, uid any, gid any) *MockContentWriter_WriteAtomic_Call {
	return &MockContentWriter_WriteAtomic_Call{Call: _e.mock.On("WriteAtomic", ctx, relPath, src, mode, uid, gid)}
}

func (_c *MockContentWriter_WriteAtomic_Call) Run(run func(ctx context.Context, relPath string, src io.Reader, mode fs.FileMode, uid int, gid int)) *MockContentWriter_WriteAtomic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 fs.FileMode
		if args[3] != nil {
			arg3 = args[3].(fs.FileMode)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockContentWriter_WriteAtomic_Call) Return(err error) *MockContentWriter_WriteAtomic_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContentWriter_WriteAtomic_Call) RunAndReturn(run func(ctx context.Context, relPath string, src io.Reader, mode fs.FileMode, uid int, gid int) error) *MockContentWriter_WriteAtomic_Call {
	_c.Call.Return(run)
	return _c
}
