// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/scality/file-reflector/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSourceReader creates a new instance of MockSourceReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSourceReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSourceReader {
	mock := &MockSourceReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSourceReader is an autogenerated mock type for the SourceReader type
type MockSourceReader struct {
	mock.Mock
}

type MockSourceReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSourceReader) EXPECT() *MockSourceReader_Expecter {
	return &MockSourceReader_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type MockSourceReader
func (_mock *MockSourceReader) Hash(ctx context.Context, relPath string) ([32]byte, error) {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 [32]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([32]byte, error)); ok {
		return returnFunc(ctx, relPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) [32]byte); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([32]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, relPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceReader_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockSourceReader_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockSourceReader_Expecter) Hash(ctx any, relPath any) *MockSourceReader_Hash_Call {
	return &MockSourceReader_Hash_Call{Call: _e.mock.On("Hash", ctx, relPath)}
}

func (_c *MockSourceReader_Hash_Call) Run(run func(ctx context.Context, relPath string)) *MockSourceReader_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceReader_Hash_Call) Return(bytes [32]byte, err error) *MockSourceReader_Hash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockSourceReader_Hash_Call) RunAndReturn(run func(ctx context.Context, relPath string) ([32]byte, error)) *MockSourceReader_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockSourceReader
func (_mock *MockSourceReader) Open(ctx context.Context, relPath string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, relPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, relPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceReader_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockSourceReader_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockSourceReader_Expecter) Open(ctx any, relPath any) *MockSourceReader_Open_Call {
	return &MockSourceReader_Open_Call{Call: _e.mock.On("Open", ctx, relPath)}
}

func (_c *MockSourceReader_Open_Call) Run(run func(ctx context.Context, relPath string)) *MockSourceReader_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceReader_Open_Call) Return(readCloser io.ReadCloser, err error) *MockSourceReader_Open_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockSourceReader_Open_Call) RunAndReturn(run func(ctx context.Context, relPath string) (io.ReadCloser, error)) *MockSourceReader_Open_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function for the type MockSourceReader
func (_mock *MockSourceReader) ReadDir(ctx context.Context, relPath string) ([]string, error) {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, relPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, relPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceReader_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockSourceReader_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockSourceReader_Expecter) ReadDir(ctx any, relPath any) *MockSourceReader_ReadDir_Call {
	return &MockSourceReader_ReadDir_Call{Call: _e.mock.On("ReadDir", ctx, relPath)}
}

func (_c *MockSourceReader_ReadDir_Call) Run(run func(ctx context.Context, relPath string)) *MockSourceReader_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceReader_ReadDir_Call) Return(strings []string, err error) *MockSourceReader_ReadDir_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSourceReader_ReadDir_Call) RunAndReturn(run func(ctx context.Context, relPath string) ([]string, error)) *MockSourceReader_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockSourceReader
func (_mock *MockSourceReader) Stat(ctx context.Context, relPath string) (domain.FileNode, error) {
	ret := _mock.Called(ctx, relPath)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 domain.FileNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.FileNode, error)); ok {
		return returnFunc(ctx, relPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.FileNode); ok {
		r0 = returnFunc(ctx, relPath)
	} else {
		r0 = ret.Get(0).(domain.FileNode)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, relPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSourceReader_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockSourceReader_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - relPath string
func (_e *MockSourceReader_Expecter) Stat(ctx any, relPath any) *MockSourceReader_Stat_Call {
	return &MockSourceReader_Stat_Call{Call: _e.mock.On("Stat", ctx, relPath)}
}

func (_c *MockSourceReader_Stat_Call) Run(run func(ctx context.Context, relPath string)) *MockSourceReader_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSourceReader_Stat_Call) Return(fileNode domain.FileNode, err error) *MockSourceReader_Stat_Call {
	_c.Call.Return(fileNode, err)
	return _c
}

func (_c *MockSourceReader_Stat_Call) RunAndReturn(run func(ctx context.Context, relPath string) (domain.FileNode, error)) *MockSourceReader_Stat_Call {
	_c.Call.Return(run)
	return _c
}
